[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/auth/google/verify"
  to = "/.netlify/functions/auth-google-verify"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
